### PR TITLE
Make the library not dependent on std

### PR DESCRIPTION
**Pull request by Pratyush**

### CODE REVIEW

**Comment by toffaletti** [comment]
Thanks for the PR. I would like to keep this targeting stable, is it possible to make this work without nightly?

**Comment by Pratyush** [comment]
Hmm. I think this is achievable by having a feature flag to turn off std (it doesn't work out of the box with `no_std` because it requires the collections and alloc features from nightly (for `Vec`). I'm a bit busy at the moment with other things, but I'll modify the pull request when I have some progress.

**Comment by Pratyush** [comment]
Hi, I fixes the issue with nightly compilation along with the following:

1. Clean up of the source code formatting using `rustfmt`
2. A pass using `clippy` (I didn't fix all errors because some weren't applicable).
3. Support for `no_std` that doesn't require nightly support for `std` users.
4. Support for `serde` for both `std` and `no_std` users.

Cheers! Let me know if anything needs work.

**Comment by toffaletti** [comment]
@Pratyush Thanks, I need to take some time to understand these changes. While I know what serde, is, I haven't used it yet. I'm also not terribly familiar with all of the compiler options you're using for no_std.

**Comment by Pratyush** [comment]
I updated the pull request to simplify the features used and cleaned up the code. In summary:

- The library now supports `no_std` + `alloc`. It is `std` by default; `alloc` mode can be enabled by setting `default-features = false` in `Cargo.toml`.
- I added optional support for `serde` behind the feature flag `serde1`. `serde` runs in `alloc` mode by default. If a crate using `flat_map` uses `serde` in `std` mode, the `serde` used by flat_map will automatically get upgraded (Cargo features are additive).

**Comment by toffaletti** [comment]
Thanks!

**Comment by Pratyush** [comment]
Would it be possible to get a new release on crates.io? Thanks!

**Comment by toffaletti** [comment]
@Pratyush I pushed 0.0.5. Please open a PR to update Cargo.toml if you'd like to be added to authors list.

**Pull request merged**
