### PR TITLE
implement IndexMut trait

### PR DESCRIPTION
**Pull request by thejinx0r**
I'm new to rust so I'm not sure if what I did was the best but I followed the same pattern as the trait Index and added a test for Index and IndexMut trait since I didn't find a test for the Index trait.

I also bumped the version.

### CODE REVIEW

**Comment by toffaletti** [comment]
Would you also like to add yourself to the contributors?

**Comment by thejinx0r** [comment]
I don't know what the implications are.
My contribution small enough that I don't need recognition, so I will say no to adding my self to the contributors.

**Comment by toffaletti** [comment]
It is up to you, but my view is that no contribution is small enough to preclude recognition.

The only implication, besides the recognition, is that if at some future time it is decided to change the license to the code we’d contact you about accepting the relicensing of your code.

**Comment by thejinx0r** [comment]
That's a good philosophy to have about the contributions, but I think the list would get really long once enough people make contributions to it and use it. It would be a good problem to have I suppose.

In any case,  I was going to write something like this but  I didn't think it was unnecessary: 
In case of a license change proposal on the flat_map project that requires my consent, I authorize @toffaletti  to make a decision on my behalf.

**Pull request merged**
